### ISSUE TITLE
Issues on OSX 10.11

### ISSUE THREAD

**Issue by toomim** [hkgumbs/multi#1]
Hello! This project is exciting. I'm trying to run it on OS 10.11 (perhaps the best version of OSX?), which has Swift 3.0.2. I'm running into these problems:

```
$ ./create-mac-app name icon.png
Package.swift:12:5: error: argument 'targets' must precede argument 'dependencies'
    targets: [
    ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
```

This was easy to fix by re-ordering `targets` and `dependencies` in Package.swift like this:
```
    targets: [
        .target(name: "Multi"),
    ],
    dependencies: [
    ]
```

But now I'm getting this error:
```
Package.swift:5:22: error: incorrect argument label in call (have 'name:products:targets:dependencies:', expected 'name:pkgConfig:targets:dependencies:')
let package = Package(
                     ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
```

I'm not sure what to do about this one. I'm not a Swift export, unfortunately.

**Comment by hkgumbs** [comment]
👋🏾@toomim

Swift 3 _should_ work OK, with the exception of [this customer User Agent line](https://github.com/hkgumbs/multi/blob/c0256a8053e79a3027b87273e1e1fa0421202185/Sources/Multi/Browser.swift#L36-L38). I don't have the means to test, but I looked at [this blog post](https://swift.org/blog/swift-package-manager-manifest-api-redesign/) that describes the major difference between Swift 3/4 `Package.swift` manifests. I think something like this would be valid in Swift 3;

```swift
import PackageDescription

let package = Package(
    name: "Multi",
    targets: [
        .Target(name: "Multi"),
    ],
    dependencies: [
    ]
)
```

Let me know if that works! If so, I'll look into conditionally using that syntax based on the Swift version (seems like a thing that should be possible)

**Comment by toomim** [comment]
Thanks for this idea! Now `create-mac-app` produces this error:
```
Package.swift:6:10: error: type 'Target' has no member 'Target'
        .Target(name: "Multi"),
         ^~~~~~
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: invalid manifest format
```

I also tried downcasing `Target` to `target`, but the error remains.

**Comment by toomim** [comment]
I made some progress. Reading this line from the [blog post](https://swift.org/blog/swift-package-manager-manifest-api-redesign/) you linked:

![image](https://user-images.githubusercontent.com/101208/82714045-efe83000-9c41-11ea-909f-1bc618db1814.png)

...I got me thinking that maybe I could just let the compiler implicitly declare those targets. So I deleted the targets line, and just left the following:

```
import PackageDescription

let package = Package(
    name: "Multi"
)
```

Now it's actually trying to compile! I'm looking a bunch of compiler errors now.

**Comment by toomim** [comment]
The first compiler error was simple to fix: multi-line strings with `"""` don't exist in Swift v3, so I converted those to single-line strings.

Now I'm seeing these remaining errors:
```
multi/Sources/Multi/Browser+all.swift:7:28: error: use of undeclared type 'Decodable'
    private struct Config: Decodable {
                           ^~~~~~~~~
multi/Sources/Multi/Browser+all.swift:22:31: error: use of unresolved identifier 'JSONDecoder'
        guard let json = try? JSONDecoder().decode([Config].self, from: file) else {
                              ^~~~~~~~~~~
Security.CMSDecoder:1:14: note: did you mean 'CMSDecoder'?
public class CMSDecoder {
             ^
multi/Sources/Multi/Browser.swift:22:22: error: type 'NSWindow' has no member 'BackingStoreType'
            backing: NSWindow.BackingStoreType.buffered,
                     ^~~~~~~~ ~~~~~~~~~~~~~~~~
multi/Sources/Multi/main.swift:23:27: error: type 'NSApplication' has no member 'ActivationPolicy'
NSApp.setActivationPolicy(NSApplication.ActivationPolicy.regular)
                          ^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
AppKit.NSApplication:43:15: note: did you mean 'activationPolicy'?
    open func activationPolicy() -> NSApplicationActivationPolicy
              ^
```

**Comment by hkgumbs** [comment]
Just emailed you using your GitHub email. I think these would be easier to work through if we could pair on it directly. Major version changes with Swift are kind of a pain.

**Comment by hkgumbs** [comment]
@toomim I used some CI-driven-development to get a working (I think) `swift3` branch. Let me know if that does/doesn't work for you. Feel free to re-open the issue if things don't go smoothly!

**Comment by toomim** [comment]
Very cool! It mostly compiles now:

```
Creating cheese.app...
Compile Swift Module 'Multi' (6 sources)
Linking ./.build/debug/Multi
cp: .build/x86*/debug/Multi: No such file or directory
```
Is that x86* thing right? On my machine there is no x86 directory:

```
$ ls -al .build/debug
total 196
drwxr-xr-x+  8 toomim    272 May 24 14:47 .
drwxr-xr-x+  5 toomim    170 May 24 14:50 ..
drwxr-x---+  4 toomim    136 May 24 14:47 ModuleCache
-rwxr-xr-x+  1 toomim 171416 May 24 14:47 Multi
drwxr-x---+ 34 toomim   1156 May 24 14:47 Multi.build
drwxr-xr-x+  3 toomim    102 May 24 14:47 Multi.dSYM
-rw-r--r--+  1 toomim    612 May 24 14:47 Multi.swiftdoc
-rw-r--r--+  1 toomim  22280 May 24 14:47 Multi.swiftmodule
```

**Comment by hkgumbs** [comment]
Ah so close! I think you can just remove the `/x86*` part of that script. I just pushed that change to the `swift3` branch 🤞🏾

**Comment by toomim** [comment]
Awesome!!!!! That totally compiled, linked, and built!

```
$ ./create-mac-app cheese ~/images/holy-cheese.png --update
Updating cheese.app...
Compile Swift Module 'Multi' (6 sources)
Linking ./.build/debug/Multi
Done!
```

And I can run it!

But ... it crashes:

```
Process:               Multi [43016]
Path:                  /Users/USER/*/cheese.app/Multi
Identifier:            sexy.kofi.multi.cheese
Version:               0.1 (0.1.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Multi [43016]
User ID:               501

Date/Time:             2020-05-24 21:30:29.738 -0700
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Unrecognized selector -[Multi.Browser methodForSelector:]
 
abort() called
```

**Comment by hkgumbs** [comment]
Just pushed https://github.com/hkgumbs/multi/commit/f44071ba856948af689877ca8de11a06c143dff3 which should resolve that crash.

**Comment by toomim** [comment]
AND IT RUNSS!!!!!!!!!

Celebration!!!!!!!!

But I have a question -- are the items in the view menu supposed to be greyed out like this?
![image](https://user-images.githubusercontent.com/101208/82859665-381a8300-9ecc-11ea-9f5a-86b4f1dd4aac.png)

**Comment by hkgumbs** [comment]
I think we're in the final stretch. Thanks for working with me on this! I just pushed https://github.com/hkgumbs/multi/commit/b6df15a3d7e425638ef197c249b5c1095951b455 which I think resolves it.

**Comment by hkgumbs** [comment]
I made a bunch of changes to Multi over the last couple weeks, and things should be a lot simpler to setup in general. For starters, you no longer need to compile stuff yourself! So this issue shouldn't apply anymore. You can learn more about how things work now on the new [README](https://github.com/hkgumbs/multi#readme).

**Comment by toomim** [comment]
Thanks @hkgumbs. :) I was able to get El Capitan to work with the changes you pushed.

I'm actually unable to get 2.0 to work on El Capitan, though, it's crashing.. but I'm also starting to feel that El Capitan just isn't supported by new software anymore. I might be switching to linux instead.

**Comment by hkgumbs** [comment]
Gahhh I thought getting rid of the build step would eliminate the version nuances. I guess that was naive. Do you have a crash report you could paste here? 10.11 is the minimum version I'm aiming to support.

**Comment by toomim** [comment]
This looks like the problem:
```
Dyld Error Message:
  Symbol not found: _$s15_ObjectiveCTypes01_A11CBridgeablePTl
  Referenced from: /Volumes/VOLUME/Multi.app/Preferences
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Volumes/VOLUME/Multi.app/Preferences
```
