### ISSUE TITLE
Refresh (command + R)

### ISSUE THREAD

**Issue by forrestnash** [hkgumbs/multi#13]
Another small thing missing from the browser: being able to refresh. Lower priority for us, but just wanted to record it in case you continue working on this for a while. 

Thanks again for making it!

**Comment by hkgumbs** [comment]
@forrestnash I pushed a change which sets Cmd-R to reload the current tab. You can update your apps by `git pull`-ing the changes then running `./create-mac-app APP_NAME ICON_PATH --update`
