### ISSUE TITLE
Reconsider the licensing strategy

### ISSUE THREAD

**Issue by jacobisaliveandwell** [hkgumbs/multi#18]
I realize this is going to a be a touchy subject. I'm sorry for that.

I really think you should reconsider the trial period. I can't tell you how much mac software I've uninstalled from engineers' laptops and replaced with other alternatives because this unsustainable pattern. You've done great work here, and you shouldn't detract from it by forcing people to pay. Sure, you'll make money, but you'll also join the stack of niche macos software that never gets anywhere beyond it's loyal following and is eventually unmaintained.

I think you'd have much much much more success keeping this FOSS, waiting for interest to build, and then license support to companies and/or have paid bounties for development. I can only say that at my company (fortune 100) we started chatting about using Multi, and that discussion was completely thrown out the window today.

It's a bummer that I'm uninstalling Multi today.

**Comment by hkgumbs** [comment]
Hmm it seems like the licensing terms weren't clear on the README? That must have caught you by surprise—sorry about that. I'll try to think of how the licensing terms clearer.

Multi is FOSS right now (under GPLv3), and I'm planning to keep it that way. It's important to keep in mind that the "F" in FOSS doesn't mean $0—it means that you have the freedom to use, copy, study, and change the software in any way. The message prompting you for a license is entirely skippable, and you can continue using Multi without supporting its development.

**Comment by jacobisaliveandwell** [comment]
@hkgumbs No, this isn't a matter of lack of clarity or inability to skip the message. This is about adoption and optics.

> The freedom to redistribute copies so you can help others
> The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

> Since Multi is open source, and since I've made no attempt to obfuscate the code, you could remove the license check and recompile the project. Please don't do that. I'd like to continue improving Multi with new features and bug fixes, and license purchases enable me to do so.

You explicitly tell people not to compile and release the free version. It's a threat that if you don't make enough money, you'll make this private.

I wish you the best of luck.

**Comment by hkgumbs** [comment]
There is no threat to make this private. Multi will continue to be a public, open source project. You'd have to look up the specifics of what you have in mind, but compiling and releasing an alternative version of Multi might be well within your rights under GPLv3.

**Comment by jacobisaliveandwell** [comment]
Correct. AFAIK, anyone can publish any fork up to the point you change the license. But history has shown that has little value in practice (there are a lot of blog posts about this). As is implicit in your request for support; there are only so many engineering hours that we all have.

Either way. Sorry, don't want to drag this out. I think I've conveyed my position. Thanks again, it was fun to play with.
