### ISSUE TITLE
Image not found Mac OS 

### ISSUE THREAD

**Issue by umang94** [hkgumbs/multi#2]
Getting this error on trying to load a newly [downloaded icon](https://img.icons8.com/color/48/000000/internet-folder.png)
```
➜  multi git:(master) ./create-mac-app hotlist /Users/umanjain/Downloads/icons8-internet-folder-100.png
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-build
  Reason: image not found
./create-mac-app: line 26: 74897 Abort trap: 6           swift build
```

**Comment by hkgumbs** [comment]
It looks like this is an issue with Swift and not your icon. Do you have XCode installed? I found [a fix in this StackOverflow post](https://stackoverflow.com/a/55440343), but I think it would only work if you have the full XCode installed (i.e. not just the Command Line Tools)?

**Comment by umang94** [comment]
I do not have xcode installed but I am trying to install it recently. I will soon let you know.

**Comment by hkgumbs** [comment]
I made a bunch of changes to Multi over the last couple weeks, and things should be a lot simpler to setup in general. For starters, you no longer need to compile stuff yourself! So this issue shouldn't apply anymore. You can learn more about how things work now on the new [README](https://github.com/hkgumbs/multi#readme).
