### ISSUE TITLE
Typo in "Window" Menu ("Minimze")

### ISSUE THREAD

**Issue by alechemy** [hkgumbs/multi#20]
https://github.com/hkgumbs/multi/blob/b970412498dd0543dfe8ce791992dcf41cc72bfd/Sources/Runtime/main.swift#L23

**Comment by hkgumbs** [comment]
Nice catch, thank you!

**Comment by alechemy** [comment]
Np! I opened a PR. But feel free to just take care of it yourself if you'd prefer, lol.

Keep up the great work! This app is awesome.

**Comment by alechemy** [comment]
Oh nvm, looks like you already fixed it! 🏎️
