### ISSUE TITLE
Allow downloads/pop-ups in certain apps

### ISSUE THREAD

**Issue by contentkraft** [hkgumbs/multi#25]
Multi apps don’t seem to allow downloads, which might be due to the Better blocker as pop-ups are also blocked. Is it possible to allow the download of files/images somehow? I can’t download files from Slack and other apps. There’s an option to download them, but nothing happens.

**Comment by hkgumbs** [comment]
This is released in https://github.com/hkgumbs/multi/releases/tag/v2.0.4

**Comment by contentkraft** [comment]
This doesn’t seem to work for me. I’m getting the following error in Slack Multi:

> Please allow pop-ups in your browser. You can contact Slack if you need help.

And it opens my default web browser (Firefox) if I attempt to download a file, but I’m not using FF for work-related things (I use Safari, but it’s not the default browser).

**Comment by hkgumbs** [comment]
@contentkraft I see that message also, but the file does then download when opened in the default browser. Are you saying that the Slack file _doesn't_ download in your default browser?

I don't think there's a way to avoid that message given the WebKit API (https://github.com/hkgumbs/multi/commit/ca6b9394d12cdc2ee06e8d9ff9febe78b20a55e7) without dynamically creating web views in Multi. I'm trying to avoid that route for now.

**Comment by contentkraft** [comment]
No, it doesn’t download. I would have to be signed in to Slack, which I’m not on Firefox as I use it for personal things as opposed to Safari for work-related things. Right now, it just copy-pastes the direct file URL to Firefox, but nothing happens.

The only way for it to work would be to make Safari the default web browser I guess?

I might have to set up a completely separate account on macOS just for work-related things so the Multi Apps don’t interfere with private stuff 😅

**Comment by hkgumbs** [comment]
Ah that makes sense. Thanks for explaining your setup. I think I can add a config field that lets you set which browser Multi opens new windows with. Something like this:

```
"openNewWindowsWith": "com.apple.Safari"
```

This feature would require that you're at least on macOS 10.15 Catalina (https://developer.apple.com/documentation/appkit/nsworkspace/3172702-open). Would that work for you?

**Comment by contentkraft** [comment]
Yep, that should work!

**Comment by hkgumbs** [comment]
Released the new configuration option in https://github.com/hkgumbs/multi/releases/tag/v2.0.6. It works just like I described above—the `openNewWindowsWith` option goes in the top-level of the JSON. There's an example on the README.

**Comment by contentkraft** [comment]
That works! Thanks so much.

**Comment by clinejj** [comment]
I seem to be getting a related issue with Gmail and Google Calendar, where clicking any link to another site in Gmail causes it to open an alert with:

"Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window."

and the browser opens but the link does not get passed into it. If I use the `openNewWindowsWith` set to Safari.

With Chrome as my default browser and no `openNewWindowsWith` config, I also get a MacOS popup that says "The application can’t be opened. -50". This looks to be something with how Gmail/Calendar handle links?

**Comment by hkgumbs** [comment]
@clinejj I pulled your note out into a new issue (#34). I have a pretty busy week, but it's at the top of my queue!

**Comment by clinejj** [comment]
No worries, thanks for the quick response!
