### ISSUE TITLE
NSInvalidArgumentException on created app launch

### ISSUE THREAD

**Issue by addiebarron** [hkgumbs/multi#29]
Big "[App] quit unexpectedly" when launching any app created with Multi 2.0.4 on Mac OS 10.13.6. This comes directly after resolving my swift runtime issue (#28), though not sure if they're related.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSMenu setItemArray:]: unrecognized selector sent to instance 0x604000269b00'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by hkgumbs** [comment]
I'm planning to look into this today. Was there a larger stack trace that appeared when Multi crashed?

**Comment by addiebarron** [comment]
Here's the full crash report: https://pastebin.com/CMpPgghY

**Comment by hkgumbs** [comment]
Just released a fix for this https://github.com/hkgumbs/multi/releases/tag/v2.0.5

**Comment by hkgumbs** [comment]
Hi @addiebarron, just wanted to check and make sure you got Multi setup after this error.

**Comment by addiebarron** [comment]
sorry @hkgumbs, it's working perfectly now. thanks so much for the fix.
