### ISSUE TITLE
Remember window size/position

### ISSUE THREAD

**Issue by endquote** [hkgumbs/multi#30]
Whenever I open my Multi app, the window opens to the full screen. It should open at the size and position it was at last time.

**Comment by hkgumbs** [comment]
This is released in https://github.com/hkgumbs/multi/releases/tag/v2.0.7

**Comment by endquote** [comment]
Works great!

**Comment by antoineguilbert** [comment]
I experienced the same problem. I'm on the last version 3.0.0 and the app don't keep the size / position when it's closed. 
Any idea ?
