### ISSUE TITLE
Open links in background

### ISSUE THREAD

**Issue by endquote** [hkgumbs/multi#31]
A nice additional configuration setting would be to open links in the background, so they open in a new browser tab, but the browser window isn't brought to the foreground.

**Comment by hkgumbs** [comment]
If this were assigned to Cmd-Click would that work for you? Or did you mean a configuration in the JSON?

**Comment by endquote** [comment]
It would be great to have it as a config setting in the JSON. My use case is making an app out of [Feedbin](https://feedbin.com), where the whole workflow is looking through things and opening links. Cmd-Click would be no good, because the app has a "V" keyboard command to open links, though it would probably be useful in other cases.

I currently do this with [Fluid](https://www.fluidapp.com), which seems abandoned. Something like its "Open in the background" setting is what I'm after.

Thanks for your work on this. I think I've tried every similar solution and they're all abandoned, bloated, or otherwise janky.

![Screen Shot 2020-09-06 at 8 25 36 AM](https://user-images.githubusercontent.com/330010/92329192-a9fd7f00-f01a-11ea-929a-2ea718d5b202.png)

**Comment by hkgumbs** [comment]
Makes sense—glad I asked! Putting it in the JSON is actually a little easier, so I think I'll get to this over the long weekend.

**Comment by hkgumbs** [comment]
I added the config option and documented it in the README. Unfortunately, it seems like Chrome doesn't respect [the macOS API](https://developer.apple.com/documentation/appkit/nsworkspace/openconfiguration/3172704-activates) to make this happen. I tested with Firefox and Safari as well, both of which correctly open the link in the background. I suspect there's nothing I can really do to fix this in Chrome, but I'm going to keep looking around.

Anyway, the new config option is released in https://github.com/hkgumbs/multi/releases/tag/v2.0.7

**Comment by endquote** [comment]
Doesn't seem to be working for me in Multi 2.0.7 with Safari.

I tried updating an existing app, and when that didn't work I trashed the app and made a new one, but saw the same behavior.

I also tried "true" with and without quotes.

```json
{
  "tabs": [
    {
      "title": "Feedbin",
      "url": "https://feedbin.com",
      "openNewWindowsInBackground": true,
      "customCss": [
        "https://gist.githubusercontent.com/endquote/4c18985bca7d0f7a1d2b134f240c9ed5/raw/179e32e9f3bd4cc2a328f6000cc5f1959d523f99/feedbin.css"
      ]
    }
  ]
}
```

**Comment by hkgumbs** [comment]
`openNewWindowsInBackground` is a top-level config, so your JSON should look like this:

```json
{
  "tabs": [
    {
      "title": "Feedbin",
      "url": "https://feedbin.com",
      "customCss": [
        "https://gist.githubusercontent.com/endquote/4c18985bca7d0f7a1d2b134f240c9ed5/raw/179e32e9f3bd4cc2a328f6000cc5f1959d523f99/feedbin.css"
      ]
    }
  ],
  "openNewWindowsInBackground": true
}
```

**Comment by endquote** [comment]
Oh, that makes sense. Works great!
