### ISSUE TITLE
View layout bugged on 10.13.6

### ISSUE THREAD

**Issue by Etheryte** [hkgumbs/multi#4]
When run on High Sierra (10.13.6), the view layout has a fixed width & height that doesn't adapt to the window's dimensions.  

![Sample image](https://i.ibb.co/MRkndhT/Screen-Shot-2020-05-23-at-02-08-09.png)

I'm really loving the simplicity of this whole project, sadly I'm not familiar with Swift so I don't know how to figure out dynamic window sizing.

**Comment by hkgumbs** [comment]
Ok, just pushed a change that should fix it. Lemme know if it does/doesn't work for you.

**Comment by Etheryte** [comment]
That works wonderfully, thanks a lot for the insanely quick response.  

This tool is insanely handy and ridiculously easy to use, I cannot thank you enough for it.

**Comment by hkgumbs** [comment]
😊
