### ISSUE TITLE
Copy with Command-C not working

### ISSUE THREAD

**Issue by greggh** [hkgumbs/multi#8]
Title says it all. I created an app with 4 websites. I go to the fisrt one with Command-1. I select some text and hit Command-C. Then Command-2, and put my cursor in a box and hit Command-V and it pastes in the wrong thing. It pastes in whatever was on my clipboard before I tried all of this. So the Command-C didn't work.

**Comment by hkgumbs** [comment]
Thanks for reporting. It looks like Copy works within the right-click menu and Paste works with whatever was most recently copied. Changed the issue title to reflect that it's just the `Cmd-C` shortcut that's broken. I'm looking into why that is.

**Comment by hkgumbs** [comment]
Found out why this was happening. You can update existing apps by `git pull`-ing the changes and then running `./create-mac-app APP_NAME ICON_PATH --update`.

**Comment by greggh** [comment]
Awesome quick fix!
